version: '3'

services:
  db:
    image: postgres:14.0
    ports:
      - 15432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - PGUSER=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=iip_search_dev
    volumes:
      - postgres_data:/var/lib/postgresql/data
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - DB_URL=postgresql+psycopg://postgres:postgres@host.docker.internal:5432/iip_search_dev
    ports: 
      - "8080:80"
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data: