"""Create inscriptions and editions tables

Revision ID: 2b8d6c9669c2
Revises: 
Create Date: 2023-07-09 23:49:33.365898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b8d6c9669c2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('parsed_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('editions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('edition_type', sa.Enum('DIPLOMATIC', 'TRANSCRIPTION', 'TRANSCRIPTION_SEGMENTED', 'TRANSLATION', name='editiontype'), nullable=False),
    sa.Column('inscription_id', sa.Integer(), nullable=True),
    sa.Column('raw_xml', sa.String(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['inscription_id'], ['inscriptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('editions')
    op.drop_table('inscriptions')
    # ### end Alembic commands ###
