"""Make IIPForms <-> Inscriptions many to many

Revision ID: 8a5a770b5c93
Revises: d79773cce09f
Create Date: 2023-07-21 19:37:14.303488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8a5a770b5c93"
down_revision = "d79773cce09f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "iip_form_inscription",
        sa.Column("iip_form_id", sa.Integer(), nullable=False),
        sa.Column("inscription_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["iip_form_id"],
            ["iip_forms.id"],
        ),
        sa.ForeignKeyConstraint(
            ["inscription_id"],
            ["inscriptions.id"],
        ),
        sa.PrimaryKeyConstraint("iip_form_id", "inscription_id"),
    )

    op.drop_constraint(
        "inscriptions_iip_form_id_fkey", "inscriptions", type_="foreignkey"
    )
    op.drop_column("inscriptions", "iip_form_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "inscriptions",
        sa.Column("iip_form_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        "inscriptions_iip_form_id_fkey",
        "inscriptions",
        "iip_forms",
        ["iip_form_id"],
        ["id"],
    )
    op.alter_column("iip_writings", "note", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("iip_forms", "ana", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("cities", "pleiades_ref", existing_type=sa.VARCHAR(), nullable=True)
    op.drop_table("iip_form_inscription")
    # ### end Alembic commands ###
