"""Add fields for additional specificity

Revision ID: d79773cce09f
Revises: ab3ca78f611e
Create Date: 2023-07-21 19:22:45.979487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d79773cce09f"
down_revision = "ab3ca78f611e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("cities", sa.Column("pleiades_ref", sa.String(), nullable=True))
    op.alter_column("iip_forms", "ana", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("iip_writings", "note", existing_type=sa.VARCHAR(), nullable=True)
    op.drop_column("images", "source")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "images", sa.Column("source", sa.VARCHAR(), autoincrement=False, nullable=False)
    )
    op.alter_column("iip_writings", "note", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("iip_forms", "ana", existing_type=sa.VARCHAR(), nullable=True)
    op.drop_column("cities", "pleiades_ref")
    # ### end Alembic commands ###
